version: "3"
services:
  lotto_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile
    entrypoint: "./docker-entrypoint-dev"
    working_dir: /application
    depends_on:
      - lotto_db
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
    networks:
      proxy:
        ipv4_address: 10.200.17.3

  lotto_nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lotto_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.lotto_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.lotto_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.17.2

  lotto_db:
    image: mysql:8.0.31
    volumes:
      - ./../data/lotto/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lotto
      - MYSQL_HOST=127.0.0.1
    networks:
      proxy:
        ipv4_address: 10.200.17.4

networks:
  proxy:
    external: true
